language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

# after_success:
#   - test $TRAVIS_BRANCH = "master" && "$TRAVIS_PULL_REQUEST" = "true"
#   # - eval "$(ssh-agent -s)" #start the ssh agent
#   # - chmod 600 .travis/deploy_key.pem # this key should have push access
#   # - ssh-add .travis/deploy_key.pem
#   - git pull origin dev
#   - git pull origin master
#   - git checkout origin/dev
#   - git checkout origin/master
#   - git merge origin/dev
#   - git push origin master
