language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) && 
      [ "$TRAVIS_PULL_REQUEST" == "true" ]; then
    git pull origin dev
    git pull origin master
    git merge dev
    git push origin master
  else
    echo "This will not merge!"
  fi
