language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) && 
      [ "$TRAVIS_PULL_REQUEST" == "true" ]; then
    git merge dev
  else
    echo "This will not deploy!"
  fi
